# The image streams in this file will be the canonical reference points
# for consumers within the cluster to loosely reference these images.
#
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: cli
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-cli:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: cli-artifacts
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-cli-artifacts:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: installer
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-installer:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: installer-artifacts
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-installer-artifacts:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: tests
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-tests:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: tools
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-tools:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: must-gather
spec:
  tags:
    - name: latest
      importPolicy:
        scheduled: true
      from:
        kind: DockerImage
        name: quay.io/openshift/origin-must-gather:v4.0
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: oauth-proxy
spec:
  tags:
    - name: v4.4
      importPolicy:
        scheduled: true
      from:
        kind: DockerImage
        name: quay.io/openshift/origin-oauth-proxy-samples:v4.4
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: hello-openshift
spec:
  tags:
  - name: latest
    importPolicy:
      scheduled: true
    from:
      kind: DockerImage
      name: docker.io/openshift/hello-openshift:latest
